### ISSUE TITLE
Install file has outdated update functions

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/globalredirect#10]
e.g. `function globalredirect_update_6101`

**Comment by quicksketch** [comment]
I looked at this today and it's actually sort of tricky. These functions still exist in the D7 version of the module: https://git.drupalcode.org/project/globalredirect/-/blob/7.x-1.x/globalredirect.install

When upgrading from Drupal 7, Backdrop assumes any 7000 or higher updates are Drupal updates, but anything lower is provided by Backdrop versions. Backdrop updates typically start at 1000. But because the Drupal version will have the schema version of 6101, Backdrop thinks all updates up until that one have been executed. I'm not sure what approach would work to get these updates to execute.

**Comment by quicksketch** [comment]
I made a hack on my PR that I think will do the job. If the state system is available, it registers an update hook globalredirect_update_6999(). That update hook then resets the schema version back to 1000 so future updates can be executed. It's pretty dirty but it's the best thing I can come up with that keeps the work-around all in one place, rather than trying to hijack other module's update hooks to reset globalredirect.

**Comment by quicksketch** [comment]
Although I'm not happy about the solution, I think it's best if we merge it so that that sites have an upgrade path from Drupal 7 and we can make further updates to fix other issues Global Redirect has with its settings, such as #2.
