### ISSUE TITLE
Unsupported operand types

### ISSUE THREAD

**Issue by kthull** [backdrop-contrib/globalredirect#6]
Had an odd issue today standing up two different sites locally using Lando. Global Redirect was installed on both, and each site reported the following error when issuing drush commands:

`Error: Unsupported operand types in _globalredirect_get_settings() (line 381 of /app/docroot/modules/contrib/globalredirect/globalredirect.module)`

Disabling in the system table wasn't sufficient, but removing the module folder from the docroot unblocked the site. Lando reports PHP 7.0.33.

**Comment by jenlampton** [comment]
It looks like the issue here is that when no config file exists yet, the return value of `config_get()` is not an array, so the `+` operator should not be used. Suggested fix in https://github.com/backdrop-contrib/globalredirect/pull/9 

This problem may also be mitigated by https://github.com/backdrop-contrib/globalredirect/issues/7 (which will assure that the config file always exists for new sites)

**Comment by laryn** [comment]
I saw this today on the latest release of Global Redirect and @jenlampton fix solves it. 
RTBC

**Comment by olafgrabienski** [comment]
I've encountered this during an upgrade from D7. The change in #9 fixed it for me, thanks @jenlampton !

Phew, an upgrade wasn't the best moment to get such an error. Can a new release with the fix be published?

**Comment by quicksketch** [comment]
I was added as a maintainer today and merged https://github.com/backdrop-contrib/globalredirect/pull/9, thanks folks!
